### PR TITLE
Lean 3.7.2 and new mathlib

### PR DESCRIPTION
**Pull request by Vtec234**
Staying on the bleeding edge, plus another attempt to use `leanproject` more. `over.lean` still fails, could you fix please @b-mehta ?

### CODE REVIEW

**Comment by b-mehta** [comment]
Have you seen the CI changes made by Ed in the beck branch? It might be better to adapt those instead of the ones from master (to be honest, those should be in master anyway though)

**Comment by Vtec234** [comment]
I think the changes on master are more recent, but for now I reverted back to `leanpkg` because `leanproject` doesn't yet report errors via the exit code properly.

**Comment by b-mehta** [comment]
Sure, the changes in `beck` do have that fix

**Comment by b-mehta** [comment]
Sorted!

**Comment by b-mehta** [comment]
@Vtec234 I'm happy to merge this if you are!

**Comment by Vtec234** [comment]
Thanks! CI is happy, let's merge.

**Pull request merged**
